---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    name: {{ .Release.Name }} 
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      name: {{ .Release.Name }}
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ .Release.Name }}
      imagePullSecrets:
        - name: docker-registry
      {{ if .Values.volume.create }}
      volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}
      {{ end }}
      containers:
        - name: blockchain
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy | quote }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          {{ if .Values.volume.create }}
          volumeMounts:
          - mountPath: {{ .Values.volume.mount }}
            name: data-volume
          {{ end }}
          envFrom:
          {{ if .Values.commonConfigName }}
          - configMapRef:
              name: "{{ .Values.commonConfigName }}"
          {{ end }}
          {{ if .Values.serviceConfigName }}
          - configMapRef:
              name: "{{ .Values.serviceConfigName }}"
          {{ end }}
          {{ if .Values.commonSecretName }}
          - secretRef:
              name: "{{ .Values.commonSecretName }}"
          {{ end }}
          {{ if .Values.serviceSecretName }}
          - secretRef:
              name: "{{ .Values.serviceSecretName }}"
          {{ end }}
