apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}
spec:
  storageClassName: {{ .Values.volume.class }}
  volumeMode: {{ .Values.volume.mode }}
  accessModes:
    -  {{ .Values.volume.accessMode }}
  resources:
    requests:
      storage: {{ .Values.volume.size }}
