---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    name: {{ .Release.Name }}
  ports:
  - name: web
    port: {{ .Values.servicePort }}
    targetPort: {{ .Values.containerPort }}
