## Image
image:

## Number of Replicas
replicas: 1

## Application Ports
servicePort: 8545
containerPort: 8545

## Volume Config
volume:
  size: 8Gi
  class: do-block-storage
  mode: Filesystem
  accessMode: ReadWriteOnce
  mount: /var/ganache-cli/chaindata

## Image Pull Policy
imagePullPolicy: Always

## All env variables related to non-secret configurations (like services hostname and ports)
## are bundled into configmaps. Other sensitive data (like services credentials) is stored in
## secrets (sealed). Some configs and secrets are common to several services, while some other
## are specific to this service. This helm chart supports both config/secrets. All these
## settings are optional.

## Common Configmap Name
commonConfigName:

## Service Configmap Name
serviceConfigName:

## Common Secret Name
commonSecretName:

## Service Secret Name
serviceSecretName:
