version: '3'

services:
  truffle:
    build:
      context: ../
      dockerfile: ./compose/truffle/Dockerfile
    image: music_smart_contracts_local_truffle
    depends_on:
      - ganache-cli

  ganache-cli:
    image: "trufflesuite/ganache-cli:v6.4.2"
    command: --networkId 2833
